# Generated by Django 2.0 on 2018-01-05 07:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isDelete', models.BooleanField(default=False)),
                ('unit', models.CharField(default='500g', max_length=20)),
                ('popularity', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('stocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(max_length=200)),
                ('comment', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('recommend', models.BooleanField(default=False)),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.ClassifyInfo')),
            ],
        ),
    ]
