# Generated by Django 2.0 on 2018-01-13 07:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='comment',
            field=models.TextField(default='delicious'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='description',
            field=tinymce.models.HTMLField(default='delicious', max_length=5000),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='popularity',
            field=models.IntegerField(auto_created=True, default=12),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.23, max_digits=6),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='profile',
            field=models.CharField(default='delicious', max_length=200),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='sales',
            field=models.IntegerField(auto_created=True, default=50),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='stocks',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
