# Generated by Django 2.0 on 2018-02-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20180113_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='stocks',
            field=models.IntegerField(default=500),
        ),
    ]
